#!/bin/bash

hosts=(weiyuyl2@linux.ews.illinois.edu c0210009@linux1.cs.nctu.edu.tw wei-yu@140.113.69.95 weiyuyl2@fa16-cs241-000.cs.illinois.edu)
#host1="weiyuyl2@linux.ews.illinois.edu"
#host2="c0210009@linux1.cs.nctu.edu.tw"
#host3="wei-yu@140.113.69.95"
index=1
max_hosts=0
for host in ${hosts[@]}; do
	max_hosts=`expr $max_hosts + 1`
done
_main(){
	echo "Enter which host you want to login:"
	for host in ${hosts[@]}; do
		echo "[$index] $host"
		index=`expr $index + 1`
	done
	read n
	if [ $n -le 0 ] || [ $n -gt $max_hosts ]; then
		echo "Try again."
		exit 0
	else
		echo "sshing to [$n]"
		ssh ${hosts[`expr $n - 1`]}
	fi
}

_main
